name: EnchantGUI
version: ${version}
main: me.tychsen.enchantgui.EnchantGUIPlugin
api-version: "1.17"

authors: [Dentych, sarhatabaot]
softdepend:
    - Vault
    - PlayerPoints

permissions:
    eshop.use:
        description: Gives access to /eshop.
    eshop.admin:
        description: Gives access to /eshop reload.
    eshop.all:
        description: Gives access to all enchants and all levels of the enchants.
    eshop.enchanting-table:
        description: Gives access to the right click on enchanting table feature.

libraries:
    - net.kyori:adventure-api:4.9.2