name: EnchantGUI
version: @version@
main: me.tychsen.enchantgui.Main
api-version: "1.13"

authors: [Dentych, sarhatabaot]
dependency: Vault

commands:
    eshop:
        description: Command for the EnchantGUI plugin
        usage: Simply just /eshop